name: Run Cypress Tests

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the job on'
        required: true
        default: 'main'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18' # or any version you prefer

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run
